### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by voscausa** [jonbretman/jinja-to-js#23]
Very Interesting solution. I'm a fan of Python Jinja. But I ask myself the following. I use Jinja to render pages and fragments. I use fetch and the DOM to paste those fragments in my SPA pages. All async. Why would I render client-side in this setup? 

Example: I have a page with a table. The first GET renders the whole page. When I need to update the table I use JSON fetch requests, which returns json with rendered html fragments (fi a table body) to update the DOM. JInja is fast, templates can be pre-compiled and minified. How / where can I benefit from your interesting solution.

**Comment by jonbretman** [comment]
Having API's that return HTML is ok if all you need to do is `innerHTML = response` but a lot of client-side code needs access to the underlying data used to render the HTML (e.g. analytics). In these cases I would prefer an API that returns the data and then do the rendering in the client code. Otherwise you end up trying to extract the data from the HTML, which generally results in code that is hard to maintain/test.

If server rendering is working for your use-case though then stick with it 😄
